replicaCount: 1

image:
  backend:
    repository: alignzo-backend
    pullPolicy: IfNotPresent
    tag: "latest"
  frontend:
    repository: alignzo-frontend
    pullPolicy: IfNotPresent
    tag: "latest"

service:
  backend:
    type: ClusterIP
    port: 3001
  frontend:
    type: LoadBalancer
    port: 3000

ingress:
  enabled: false
